import { nativeWorkerRole } from "../models/plan.ts";
import { snapshotWorkerSkills } from "../workers/context.ts";
import { Type } from "typebox";
import { Value } from "typebox/value";
import { acceptMission, issueMission, revalidateWorkerMission, type WorkerMission } from "../workers/mission.ts";
import { WorkerRunner } from "../workers/runner.ts";
import { workerCanWrite } from "../workers/roles.ts";
const revisionRef = Type.Object({ artifactId: Type.String({ minLength: 1 }), revisionId: Type.String({ minLength: 1 }), digest: Type.String({ minLength: 64, maxLength: 64 }) }, { additionalProperties: false });
export const taskRequestSchema = Type.Object({ skills: Type.Optional(Type.Array(Type.Object({ name: Type.String({ minLength: 1, maxLength: 64 }), sha256: Type.String({ pattern: "^[0-9a-f]{64}$" }), resources: Type.Optional(Type.Array(Type.String({ minLength: 1, maxLength: 512 }), { maxItems: 7 })) }, { additionalProperties: false }), { maxItems: 8 })), goal: Type.String({ minLength: 1, maxLength: 4096 }), nonce: Type.String({ minLength: 1, maxLength: 128 }), role: Type.String({ minLength: 1, maxLength: 32 }), mode: Type.Union([Type.Literal("full"), Type.Literal("read-only")]), model: Type.String({ minLength: 1, maxLength: 256 }), effort: Type.String({ minLength: 1, maxLength: 32 }), criteria: Type.Array(Type.String({ minLength: 1, maxLength: 512 }), { maxItems: 16 }), commands: Type.Array(Type.Array(Type.String({ minLength: 1, maxLength: 512 }), { minItems: 1, maxItems: 32 }), { maxItems: 16 }), resultLimit: Type.Integer({ minimum: 1, maximum: 65536 }), acceptedBindings: Type.Optional(Type.Object({ changeId: Type.String(), artifactId: Type.String(), revisionId: Type.String(), digest: Type.String({ minLength: 64, maxLength: 64 }), stateVersion: Type.Integer({ minimum: 0 }), inputs: Type.Array(revisionRef, { minItems: 1, maxItems: 8 }) }, { additionalProperties: false })), exploration: Type.Optional(Type.Object({ roots: Type.Array(Type.String({ minLength: 1, maxLength: 512 }), { minItems: 1, maxItems: 16 }), maxFiles: Type.Integer({ minimum: 1, maximum: 10000 }), maxBytes: Type.Integer({ minimum: 1, maximum: 16777216 }), maxTokens: Type.Integer({ minimum: 1, maximum: 65536 }) }, { additionalProperties: false })), targets: Type.Record(Type.String({ minLength: 1, maxLength: 512 }), Type.String({ minLength: 1, maxLength: 64 }), { maxProperties: 64 }) }, { additionalProperties: false });
export function createTaskTool(host: { role: string; mode?: "full" | "read-only"; workspace: string; resolveSkills?: typeof snapshotWorkerSkills; runner?: WorkerRunner; executeWorker?: (mission: WorkerMission, signal?: AbortSignal, auth?: unknown) => Promise<string>; prepareWorker?: (mission: WorkerMission) => Promise<unknown>; supportsModel?: (model: string, effort: string) => boolean; verifyAcceptedBinding?: (binding: any) => Promise<boolean> }) { const runner = host.runner ?? new WorkerRunner(); return { name: "task", label: "Run worker", description: "Delegate one bounded mission with explicit criteria, targets, commands, and optional managed skills. Skills resources are relative paths selected after reading SKILL.md; they never expand authority.", parameters: taskRequestSchema, async execute(_id: string, input: any, signal?: AbortSignal) { if (host.role !== "manager") throw new Error("task requires manager authority"); if (!Value.Check(taskRequestSchema, input)) throw new Error("invalid task input"); if (host.mode === "read-only" && input.mode !== "read-only") throw new Error("worker mode exceeds parent authority"); const role = nativeWorkerRole(input.role); if (input.mode === "full" && !workerCanWrite(role)) throw new Error("worker role cannot request full mode"); if (role === "sdd-apply" && (!input.acceptedBindings || !host.verifyAcceptedBinding || !(await host.verifyAcceptedBinding(input.acceptedBindings)))) throw new Error("sdd worker accepted binding rejected"); if (!host.executeWorker) throw new Error("worker execution transport unavailable"); if (host.supportsModel && !host.supportsModel(input.model, input.effort)) throw new Error("worker model or effort unsupported"); const skills = input.skills?.length ? await (host.resolveSkills ?? snapshotWorkerSkills)(input.skills) : undefined; const mission = await acceptMission(issueMission({ ...(skills ? { skills } : {}), nonce: input.nonce, role, workspace: host.workspace, mode: input.mode, model: input.model, effort: input.effort, goal: input.goal, criteria: input.criteria, commands: input.commands, resultLimit: input.resultLimit, ...(input.acceptedBindings ? { acceptedBindings: input.acceptedBindings } : {}), ...(input.exploration ? { exploration: input.exploration } : {}), targets: input.targets })); const result = await runner.run(mission, async (workerSignal) => { await revalidateWorkerMission(mission); if (mission.role === "sdd-apply" && (!host.verifyAcceptedBinding || !(await host.verifyAcceptedBinding(mission.acceptedBindings)))) throw new Error("sdd worker accepted binding rejected before launch"); const auth = await host.prepareWorker?.(mission); return await host.executeWorker!(mission, workerSignal, auth); }, signal); return { content: [{ type: "text", text: JSON.stringify({ nonce: mission.nonce, role: mission.role, result: (() => { try { return JSON.parse(result); } catch { return result.slice(0, mission.resultLimit); } })() }) }] }; } }; }
