.PHONY: fast verify

fast:
	test -z "$$(gofmt -l .)"
	go test -short ./...

verify:
	test -z "$$(gofmt -l .)"
	go test -count=1 -covermode=atomic -coverprofile="$${TMPDIR:-/tmp}/vgxness-coverage.out" ./...
	go test -count=1 -race ./...
	go vet ./...
	go mod tidy -diff
	git diff --check
	go mod verify
	go build -trimpath ./...
	go test -tags=e2e -count=1 -run '^TestCleanCheckoutSetupAndNativeSDD$$' ./internal/e2e
	GOOS=windows GOARCH=amd64 go build -trimpath ./...
	GOOS=windows GOARCH=arm64 go build -trimpath ./...
	GOOS=windows GOARCH=amd64 go test -count=1 -run '^$$' -exec=/usr/bin/true ./...
	GOOS=windows GOARCH=amd64 go test -tags=e2e -count=1 -run '^$$' -exec=/usr/bin/true ./internal/e2e
