import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

export type ContractRole = { id: string; aliases: string[]; writeAuthority: boolean; instructions: string; modelRole?: string };
export type ManagerContract = { schemaVersion: "vgxness-manager-contract/v1"; identity: "vgxness-orchestration/v1"; sourceDigest: string; manager: ContractRole; roles: ContractRole[] };
const resource = join(dirname(fileURLToPath(import.meta.url)), "../../resources/orchestration/contract.json");
export function canonicalContract(value: any): string { return Array.isArray(value) ? `[${value.map(canonicalContract).join(",")}]` : value && typeof value === "object" ? `{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${canonicalContract(value[key])}`).join(",")}}` : JSON.stringify(value); }
export function loadManagerContract(path: string | URL = resource): ManagerContract { const bytes=readFileSync(path); const c=JSON.parse(bytes.toString()) as ManagerContract; const all=[c.manager,...(Array.isArray(c.roles)?c.roles:[])]; const required=["explore","general","verifier","care-reviewer","care-specialist","care-challenger"]; const names=new Set<string>(); const valid=all.every(role => { if (!role?.id || typeof role.writeAuthority!=="boolean" || !Array.isArray(role.aliases) || !role.aliases.every(alias=>typeof alias==="string") || !role.instructions?.trim() || names.has(role.id)) return false; names.add(role.id); for (const alias of role.aliases) { if (!alias || names.has(alias)) return false; names.add(alias); } return true; }); if (c.schemaVersion!=="vgxness-manager-contract/v1"||c.identity!=="vgxness-orchestration/v1"||c.manager?.id!=="manager"||c.roles.length!==6||!required.every((id,index)=>c.roles[index]?.id===id)||!c.sourceDigest||!valid||c.sourceDigest!==createHash("sha256").update(canonicalContract({schemaVersion:c.schemaVersion,identity:c.identity,manager:c.manager,roles:c.roles})).digest("hex")) throw new Error("manager contract drift"); return Object.freeze(c); }
export function resolveRole(contract: ManagerContract, role: string) { return [contract.manager,...contract.roles].find(item=>item.id===role||item.aliases.includes(role)); }
export function renderManagerPrompt(contract: ManagerContract) { return `${contract.manager.instructions}\n\n# Delegated role contract\n${contract.roles.map(role=>`## ${role.id}\nAuthority: ${role.writeAuthority ? "may write only within its bounded mission" : "read-only"}. Aliases: ${role.aliases.join(", ") || "none"}.\n${role.instructions}`).join("\n\n")}\n`; }
